### ISSUE TITLE
3.8.0 not supported on 6.7.5 (According to update center)

### ISSUE THREAD

**Issue by SMUnlimited** [spotbugs/sonar-findbugs#210]
## Issue Description

Update Center says the new 3.8.0 cannot be used on sonarqube 6.7.5 LTS. Is that expected?

![image](https://user-images.githubusercontent.com/5180431/45548256-92200580-b81b-11e8-8d7f-d9aa97ea8b83.png)

## Environment

| Component          | Version |
| ------------------ | ------- |
| SonarQube          | 6.7.5   |
| Sonar-FindBugs     | 3.8.0   |

**Comment by SMUnlimited** [comment]
Looks like update center has been fixed and is now supported again.

**Comment by VinodAnandan** [comment]
Hi Liam,

It was a mistake (compatibility information) I made it with the Request For
Feedback and New release announcement. Please do follow us in the
community.sonarsource.com. So that you can notice mistakes during RFF and
avoid mistakes and problems with any releases in the future.

https://community.sonarsource.com/t/rff-sonar-findbugs-3-8-0/2419/2
https://community.sonarsource.com/t/new-release-sonar-findbugs-3-8-0/2520/6

Thank you,

Vinod
