### ISSUE TITLE
Performance issue with sonar-findbugs-plugin(v3.4.3)

### ISSUE THREAD

**Issue by vara-prasad** [spotbugs/sonar-findbugs#41]
We are seeing performance issue with sonar-findbugs-plugin (v3.4.3) when upgraded from 3.2 to 3.4.3

The below are the observations
- sonar-findbugs-plugin-3.2 analyzes only java class files (provided by sonar.java.binaries) which have matching java sources (java files that are indexed by sonarqube)
- sonar-findbugs-plugin-3.4.3 analyzes all java class files even if java source indexed by sonarqube are not at all matching.

scanForAdditionalClasses is adding the classes from sonar.java.binaries for findbugs to scan.

Can you please let us know on why do we need to add all classes instead of using classes only from javaResourceLocator.classFilesToAnalyze() as sonarqube can only raise violations on the files that are indexed ?

**Comment by giacgbj** [comment]
Could this be related to the fact I'm experiencing a lot of 
```org.elasticsearch.transport.ReceiveTimeoutTransportException: [][127.0.0.1:9001][cluster:monitor/nodes/liveness] request_id [107739] timed out after [5000ms]````since I updated some of the plugins, including this one?

**Comment by h3xstream** [comment]
@vara-prasad 
The new scanning strategy was made on purpose.

There are two benefits :
 - The main reason is to support new languages (Currently Java and JSP .. eventually Scala, twirl, Groovy, Kotlin)
 - There is less chance that a compiled class are missed. Java to class is not a one to one relation. ([example](./40)) In the new version when the mapping can't be done a WARNING is logged. It was previously silent.

_(Personal point of view)_ FindBugs analyse bytecode. It seems more intuitive to feed all the classes to the engine. FindBugs detectors are doing much more than greping. The analysis often need contextual information such as complete inheritance tree. If a detector check for an instance implementing a interface or being annotated, it might need classes excluded from the report.

**Comment by h3xstream** [comment]
Quick note : In order to qualify this report as a bug to investigated, I will need input such as code sample, project pattern and/or metrics.

**Comment by h3xstream** [comment]
@giacgbj 
The error you are referring is triggered by Elastic Search. I think it is a separate process from SonarQube instance. The analysis of plugin such as FindBugs is all done client-side.

**Comment by vara-prasad** [comment]
@h3xstream 
The reason for performance issue is due to so many classes that needs to be scanned. 
Earlier findbugs analysis used to happen for only matched classes (with java files indexed by sonar).
Could not provide code sample / sample project as it happens when there are large number of classes to be analysed. 
One  pattern to try out is to have make  1 java file  and 50 class files available for sonar analysis. In this case all the 50 files will be scanned for findbugs rules and violation will be reported on only 1 java file for which source is indexed.

**Comment by h3xstream** [comment]
@vara-prasad Ok I understand your point.

How those classes files are generated?

**Comment by vara-prasad** [comment]
@h3xstream 
The classes are unzipped from the jars which are created as part of build process.
Consider each class as a separate java file at source (ignoring the nested and outer classes to make test case simple).
For example, source can have java files like A.java, B.Java ...  Z.java, but sonar.java.binaries will point to only one class which is A..java. In this case, all the analysis done on B.java ... Z.java will not translate to sonar violation.

**Comment by h3xstream** [comment]
@vara-prasad 
Could you do the unzip operation after the sonar analysis? Alternatively,  it could be disabled when Sonar is running ?

**Comment by vara-prasad** [comment]
@h3xstream 
In our setup, the build process and sonar scan are two independent activities.
We do not execute sonar scan on the build.
 
We copy the source files and jars to different directories (and jars will be extracted) and use these new locations to do sonar scan using sonar-scanner.

**Comment by h3xstream** [comment]
@vara-prasad I would recommend to have a more traditional setup where compilation is trigger and sonar is run. This would allow to scope the analysis to the proper classes (binary files).

1. `mvn install` / `mvn test-compile`
2. `mvn sonar:sonar`

**Comment by vara-prasad** [comment]
@h3xstream 
The suggested approach does not work for us as we will not be able to make sonar analysis as part of build process.

**Comment by starkindustry** [comment]
@h3xstream We are having similar issues with this version of the plugin. In our case, the Sonar analysis is run as part of the build after tests have run on the project. The project code and associated tests require unpacked class files which Findbugs is analyzing and eventually timing out on. Increasing the timeout threshold has sadly not worked either as we run out of memory.

**Comment by h3xstream** [comment]
@starkindustry How much memory is set for Maven/Sonar client?

**Comment by starkindustry** [comment]
@h3xstream It was originally allocated with 512M of heap. I've doubled the heap space and am running another build but we usually only use ~100M for an entire build prior to the upgrade. And in fact the class files themselves barely account for 40M. So I'm puzzled as to how the memory is being allocated.

**Comment by BlackAngelTiger** [comment]
Hi,

we are seeing the explosion of the analysis time as well. We used 3.3 and updated to 3.4.3. The Project analysis time has been changed from two minute up to 20 min per project. Which is fare to much for a CI build.

Used the versions FB 3.3 with Java 3.14 and FB 3.4.3 with Java 4.2.

**Comment by h3xstream** [comment]
@starkindustry @BlackAngelTiger 
Are you using Sonar-FindBugs to do functional analysis (Profile FindBugs / FindBugs + FB-contrib) or doing vulnerability scanning (Profile FindBugs Security Minimal / FindBugs Security Audit)

If you are doing vulnerability scanning, there are indeed major improvements and additions that were made to the plugin FSB. This could be the source of the increase. In this case you can refer, to the release notes: https://github.com/find-sec-bugs/find-sec-bugs/releases

If you are using FindBugs basic profile, the rules are pretty stable (version 3.0.1 for  the last releases). This is more surprising. You can try to scan your application with FindBugs with another integration than Sonar : 
 - Maven (mvn findbugs:findbugs)
 - IntelliJ / Netbeans / Eclipse
Let me know if you see any difference.

**Comment by snehalkunjir** [comment]
I am also facing same issue with latest sonar-findbug plugin.
I tried to use "mvn findbugs:findbugs" , its working fine. 

I've upgraded sonar-findbug plugin to latest release from 3.3 and now sonar analysis is failing with below error:

Java HotSpot(TM) 64-Bit Server VM warning: INFO: os::commit_memory(0x000000078bd80000, 550502400, 0) failed; error='Cannot allocate memory' (errno=12)
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 550502400 bytes for committing reserved memory.
# An error report file with more information is saved as:
# /jenkins/workspace/hs_err_pid28240.log
[TemplateProject] FAILED performing builders from: 'Template-CPS-trunk-JDK18'
Build step 'Use builders from another project' marked build as failure
[FINDBUGS] Skipping publisher since build result is FAILURE
Archiving artifacts

**Comment by BlackAngelTiger** [comment]
@h3xstream I have tried now the newest Version of the Plug-In with the Java 4.3.0.7717 on the SonarQube Server 5.6.3 with the a ruleset where from the FindBugs + FB-Contrib are around 220 Rules active and in FindBugs Security Audit 5 Rules and in the FindBugs Security Minimal also 5 rules.
The time was 18:48.894s

**Comment by h3xstream** [comment]
@snehalkunjir @BlackAngelTiger @vara-prasad

I am currently doing improvement to the sonar plugin. Please read my previous message. Without information, this investigation will be postponed.

**At minimum**
 - I need comparison of FindBugs stock vs Sonar-FindBugs with the same profile.
 - Stats from Eclipse Memory Analyzer (You can attach to Maven process)

**Ideally**
 - Code project to reproduce

**Informational**
 - How much memory is needed. How much memory was needed.
 - How many line of

**Comment by mikemaaaa** [comment]
For me there seems to be an issue with multi-module maven projects. I think the plugin now scans all dependencies of a module together with the module.

We have the following structure ( slightly more complex) but to explain my findings this is sufficient

root
 - A
 - B (depends on A)
 
The plugin now scans A which is rather big (1k classes). Now it scans B which has like 10 classes and also scans the dependencies (A).

2 scan runs (when running sonar:sonar) do the following - execute plugin on:

A
B and A

Some additional stuff i found:

This whole "double scanning" just happens when the artifact A is NOT installed to the local repository.

Example data from findbugs-result.xml of sub-module B:

This is without installing the artifacts: issues are found in A and A is added to the classpath via a directory
...
<Jar>...\A\target\classes\....class</Jar>
<AuxClasspathEntry>c:\dev\...\...\A\target\classes</AuxClasspathEntry>
...

Now when installing artifacts the content of the findbugs-result.xml of sub-module B looks like:

The plugin does not find issues in A anymore and A is included via the jar in the local repository
...
<AuxClasspathEntry>C:\Users\...\.m2\repository\...\A\1.0.0-SNAPSHOT\a-1.0.0-SNAPSHOT.jar</AuxClasspathEntry>
...

Also the time it took to run sonar:sonar seems to be consistent:

without installing snapshots:

[INFO] Total time: 09:14 min

with installing snapshots:

[INFO] Total time: 07:11 min

It takes about 2 mins for findbugs to scan A which explains the 2 additional minutes when scanning A twice.

Hope this helps to identify the actual issue :)

**Comment by BlackAngelTiger** [comment]
Hi,

we switched from ant to gradle and I included there SonarQube as well. Also I increased the CPU cores (from 2 to 4) and the ram (from 2 to 4) also I extended the jvmargs from the normal 2048m to 4096m and I did not have the problem any more. May be it helps you to to increase the ram, because I think this was the problem here.

Best Regards

PS: When I have tim I hope to give you the informations you asked for.

**Comment by simsandyca** [comment]
Hi, 
This is blocking our sonarqube process also.  After upgrading to sonarqube 5.6 sonar-scanner 2.9 and findbugs plugin 3.4.4 our scan time jumped from about 2 hours to 24 hours.

**Comment by simsandyca** [comment]
I was able to get our sonar-scanner analysis going again by uninstalling the findbugs plugin in sonarqube.  I configured a separate findbugs run on our build using the gradle plugin https://docs.gradle.org/current/userguide/findbugs_plugin.html.  Separated out, findbugs takes about 35 minutes to run on our code.

**Comment by h3xstream** [comment]
@vara-prasad Let me know if the current version is still causing this.

You can do the scanning from FindBugs/SpotBugs Maven plugin and Sonar will pick it up. You might be able to control the scanning better with the Maven plugin.

**Comment by mikejhill** [comment]
I know this issue has been closed for a long time, but I came across this while diagnosing long SonarQube scans for our repo and figured I'd share my findings for any future visitors.

Our problem was specifically related to running SonarQube scans with Gradle with multi-module builds. We rules enabled from FindBugs, FB-Contrib, FSB, and a number of other repositories. We have a mid-sized multi-project build with about 50 modules and < 1m LOC, mostly Java. Full SQ scans were taking ~90 minutes, which was prohibitive for us for anything but nightly scans.

From looking at findbugs-results.xml, it was clear we were hitting the duplicate analysis issue mentioned by some previous posters. The cause of this was the default `sonar.java.libraries` config from the Gradle SonarQube plugin. The plugin uses the main and test source set compile class paths as `sonar.java.libaries` and `sonar.java.test.libraries` when running scans. This is fine for most purposes, but causes a problem with FindBugs analysis since FB seems to want to scan all .class files in the libraries list (but is fine with JARs).

I was able to cut the scan time from ~90 minutes to ~18 minutes by modifying the properties to pull in the runtime class path (which uses JARs from upstream projects) instead of the compile class path (which uses upstream class files directly). This isn't exactly what I'm using to configure the extension properties, but it's close to it:
```kotlin
val javaHome = System.getProperty("java.home")
property("sonar.java.libraries", project.the<SourceSetContainer>()["main"].runtimeClasspath.files.filter { it.exists() }.map { it.toString() }
        + (properties["sonar.java.libraries"] as Collection<*>).filter { it.toString().startsWith(javaHome) }) // Retain existing JDK library entries
property("sonar.java.test.libraries", project.the<SourceSetContainer>()["test"].runtimeClasspath.files.filter { it.exists() }.map { it.toString() }
        + (properties["sonar.java.test.libraries"] as Collection<*>).filter { it.toString().startsWith(javaHome) }) // Retain existing JDK library entries
```

Hopefully that helps someone out there as much as it would have helped me.
