### ISSUE TITLE
Can not execute Findbugs: One (sub)project contains Java source files that are not compiled in Scala folder 

### ISSUE THREAD

**Issue by Joyvalley** [spotbugs/sonar-findbugs#504]
Hi, 
we are running a job with the following set up:
Sonarqube 9.3
Maven 3.6.3 
bamboo server v8.1.1
Findbugs 4.0.6 
and get the following error message from findbugs:

Can not execute Findbugs: One (sub)project contains Java source files that are not compiled
The problem is that the folder in question does not contain any java code but has scale code in it, with files that end with .scala so they should be distinguishable from java sources. 

We can of course mitigate the issue by the following:
1. Ignore the folder that causes the error by adding -Dsonar.exclusions=parser-generator/** to the additional parameters.
2. Allowing uncompiled code in the analysis by adding -Dsonar.findbugs.allowuncompiledcode to the additional parameters
3. Select the option allowuncompiledcode in sonarqube project settings
4. Set the sonar.java.sources variable 
5. Add java-dummy code that gets compiled to the folder 

This still seems like a bug, or are we doing something wrong. 
In the sonar.properties only the project name and key are passed. 

Kind regards, 
JF

**Comment by Joyvalley** [comment]
After downgrading to 4.0.5 the analysis runs without problem. So the issue was introduced in the newer version 4.0.6

**Comment by gtoison** [comment]
Hello,
Can you please share more details about the structure of the project? Otherwise it's complicated to advise
What are you building with (maven, gradle, ...), what is the language(s), where are the source and .class files?
I suspect that this is caused by https://github.com/gtoison/sonar-findbugs/commit/59e79cd036d3c72d2149e32daf5d2495c96ec03e but I won't be able to reproduce without more details

I started maintaining the project relatively recently, although the former maintainers are no longer active here it seems like Scala was never really supported: https://github.com/spotbugs/sonar-findbugs/issues/292

I tried to revive an old PR (https://github.com/spotbugs/sonar-findbugs/pull/237#issuecomment-1013649498) to give Scala support but I did not get any traction. Since I don't know Scala myself I would probably need some kind of guinea pig to test it!
Let me know if you're interested

**Comment by gtoison** [comment]
The error messages about node.js are from SonarQube itsefl, not from the SpotBugs plugin, so I don't know what's causing them and it shouldn't be related to the other error message: _Can not execute Findbugs: One (sub)project contains Java source files that are not compiled (///abce-server-parent/***-war)_

Can you please share more details about the folder structure of the project? What are you building with (maven, gradle, ...), what is the language(s), where are the source and .class files?
I don't know what's causing the problem and would need more information to reproduce it

**Comment by Joyvalley** [comment]
Hi, 
thanks for your reply. 
we are building java 11 and the project is a multi-maven application with different modules. There is one module that only contains scala code and this module is causing the issue, since the upgrade to findbugs 4.0.6. The class files are in the target folders and the source files are in src/main/scala/ .
I believe findbugs should ignore that folder as there are no java sources in there just scala sources and their according compiled classes. 
The error message: One (sub)project contains Java source files that are not compiled suggests that findbugs is looking for java sources and their compilations. 
We have now downgraded to version 4.0.5 and the issue disappeared again. 
Kind regards, 
JF

**Comment by gtoison** [comment]
Thank you for the update @Joyvalley 
I will check how the plugin handles maven multi module/language projects.
Spotbugs works by analyzing the .class files and then the SonarQube plugin tries to tie the finding to the source code file, that's why it is complaining when it cannot find .class files

Before version 4.0.6 there was issue https://github.com/spotbugs/sonar-findbugs/issues/275 where it would analyze the .class of multi-module projects for each dependent module, so the analysis time was a lot longer than it should be. Since you have a multi module project I'll start by looking there

**Comment by gtoison** [comment]
Scala code should be analyzed in the latest version (4.1.3) of the plugin, so please consider testing, this should fix the issue
Please let me know if there's any other problem
