### ISSUE TITLE
New configuration: Skip project/submodule that are not compiled

### ISSUE THREAD

**Issue by h3xstream** [spotbugs/sonar-findbugs#56]
Regarding this situation #46, the most accommodating option would be to have an option to ignore missing compiled code.

Since the validation is needed for 99.9% of projects, it should not be enable by default.

**Comment by lolnoob** [comment]
I have some java code in the project which requires only static analysis and is never build. Hence the need for Findbug disables SQ analysis of my project.
Do you have any idea on when this enhancement may be introduced to the plugin?

**Comment by olaoluphilip** [comment]
Maybe this might help in fixing the issue. I get this error when I analyze the project from Bamboo but successful when I run it locally

**Comment by acartapanis** [comment]
Sorry but to me this is not an enhancement, this is a bug.  
I have a huge project with many resources-only jar, and I cannot use sonarqube on it for now.  
The only way i find to make my projects analyzable is to remove the findbugs plugin, wich is sad to me.

**Comment by hohwille** [comment]
I am facing the same issue. I do have projects with packaging `jar` or `war` but no single Java class. Then this plugin fails and I can not do the sonar analysis if findbugs is activated.

E.g. a simple example is a project where I do have a spring boot application that I want to build as a regular JAR in order to still use it as a regular dependency but then I also need another module of packaging `war` that simply converts the JAR into a bootified WAR. This project does not have a single Java class and hence it fails with

```
[WARNING] Findbugs needs sources to be compiled. Please build project before executing sonar or check the location of compiled classes to make it possible for Findbugs to analyse your (sub)project (...).
```
Example:
https://github.com/oasp/my-thai-star/tree/develop/java/mtsj

**Comment by hohwille** [comment]
Already according to the logged message this is a bug:
* all sources are compiled (if there are no sources)
* I did build the project before executing sonar so also the suggested hint is wrong.

**Comment by h3xstream** [comment]
Implemented
